# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/000bb2d1-dfb8-4281-8b98-69deda610f58";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/000bb2d1-dfb8-4281-8b98-69deda610f58";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/000bb2d1-dfb8-4281-8b98-69deda610f58";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6070-5C1F";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/games" = 
   { device = "/dev/disk/by-uuid/000bb2d1-dfb8-4281-8b98-69deda610f58";
     fsType = "btrfs";
   };

  fileSystems."/swap" = 
   { device = "/dev/disk/by-uuid/000bb2d1-dfb8-4281-8b98-69deda610f58";
     fsType = "btrfs";
   };

  swapDevices = [{ 
   device = "/swap/swapfile"; 
   size = 8*1024;
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
